import { Link, Route, Routes } from 'react-router-dom'
import { features, release, routes } from './data/project'
const slug = (name: string) => name === 'Home' ? '/' : `/${name.toLowerCase()}`
function Page({ title, children }: { title: string, children: React.ReactNode }) { return <main className="page"><p className="eyebrow">OBSIDIAN LINUX</p><h1>{title}</h1>{children}</main> }
function Home() { return <Page title="A focused Debian desktop."><p className="lede">Obsidian Linux is a Wayland-first distribution built around Labwc, Calamares, and a restrained visual language.</p><div className="actions"><a className="button" href={release.url}>View releases</a><Link className="link" to="/features">Explore features</Link></div><section><h2>Built for a calm, capable desktop</h2><ul>{features.map(feature => <li key={feature}>{feature}</li>)}</ul></section></Page> }
function Download() { return <Page title="Download"><p>Current channel: <strong>{release.status}</strong>. Release images, checksums, Flatpak bundles, and notes are published through GitHub Releases.</p><a className="button" href={release.url}>Open latest release</a><p className="quiet">Architecture: {release.architecture} · Base: {release.base} · Desktop: {release.desktop} · Installer: {release.installer}</p></Page> }
function Screenshots() { return <Page title="Screenshots"><p>Verified screenshots are captured only from a running Obsidian Linux ISO.</p><div className="empty"><strong>Capture pending</strong><span>Build and boot the ISO, then add sanitized captures to <code>website/public/screenshots</code>.</span></div></Page> }
function Generic({ title }: { title: string }) { return <Page title={title}><p>Project information for {title.toLowerCase()} is maintained alongside the distribution source.</p>{title === 'Features' && <ul>{features.map(feature => <li key={feature}>{feature}</li>)}</ul>}{title === 'Applications' && <p>Obsidian applications are delivered as native Debian packages or optional Flatpaks according to their privilege requirements.</p>}{title === 'Documentation' && <a className="link" href="https://github.com/YOUR-USERNAME/obsidian-linux/tree/main/docs">Read documentation</a>}</Page> }
export function App() { return <><header><Link className="brand" to="/"><img src="/obsidian-linux/favicon.svg" alt=""/>Obsidian Linux</Link><nav aria-label="Primary">{routes.map(route => <Link key={route} to={slug(route)}>{route}</Link>)}</nav></header><Routes><Route path="/" element={<Home/>}/><Route path="/download" element={<Download/>}/><Route path="/screenshots" element={<Screenshots/>}/>{routes.filter(route => !['Home','Download','Screenshots'].includes(route)).map(route => <Route key={route} path={slug(route)} element={<Generic title={route}/>}/>)}</Routes><footer>Obsidian Linux · MIT License · Development Preview</footer></> }
