---
modules-search:
  - /usr/lib/x86_64-linux-gnu/calamares/modules
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - timezone
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - hostname
      - displaymanager
      - networkcfg
      - grubcfg
      - bootloader
  - show:
      - finished
branding: obsidian
