#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free-firmware" \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet splash" \
  --debian-installer live \
  --debian-installer-gui false \
  --firmware-binary true \
  --firmware-chroot true \
  --linux-flavours amd64 \
  --system live \
  --apt-recommends false \
  --checksums sha256 \
  --memtest none \
  --bootloader grub-efi
